[package]
name = "hiit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = { version="0.6.2", features = ["gnome_44", "libadwaita"] }
relm4-components = "0.6.2"
relm4-macros = "0.6.2"
tokio = { version = "1.28", features = [
    "rt",
    "macros",
    "time",
    "rt-multi-thread",
] }
