from_latest_tag = true
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "grep version=\\\"{{version}}\\\" data/xyz.safeworlds.hiit.metainfo.xml.in",
    "sed -i \"s|version: '[0-9]\\+.[0-9]\\+.[0-9]\\+'|version: '{{version}}'|\" meson.build"
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "exercise-timer"
owner = "mfep"
template = "remote"
authors = [
    { signature = "Lőrinc Serfőző", username = "mfep" }
]

[bump_profiles]

[packages]
